chore: update python version support to 3.11 and 3.12 for tests
openedx/openedx-learning pull request #163
Opened 2024-02-20 12:03 UTC by salman2013

2024-02-28 14:02 UTC, farhan requested changes

2024-02-28 14:02 UTC, farhan commented on tox.ini
> +    setuptools
I think we have defined setuptools in default [testenv] and no need to define in others

2024-02-28 14:02 UTC, farhan commented on requirements/test.txt
> +<<<<<<< HEAD
Conflict is not resolved here

2024-02-28 14:02 UTC, farhan commented on requirements/quality.txt
> +# This file is autogenerated by pip-compile with Python 3.12
Please verify whether we have to auto-generate on 3.8 or 3.12

2024-02-28 16:04 UTC, ormsbee commented on tests/openedx_learning/core/publishing/test_api.py
> +        # assert package.created.tzinfo == timezone.utc
Making sure that timestamps are written in UTC is actually important for this app, so I'd really like to understand why this breaks.

2024-03-04 11:24 UTC, farhan approved these changes

2024-03-04 11:40 UTC, merged