Upgrade DRF
openedx/openedx-learning pull request #175
Opened 2024-03-26 08:04 UTC by farhan

Upgrade DRF

2024-04-04 09:10 UTC, awais786 commented on openedx_tagging/core/tagging/models/import_export.py
> +class TagImportTaskState(models.TextChoices):
https://docs.djangoproject.com/en/5.0/ref/models/fields/#enumeration-types

2024-04-04 14:29 UTC, irtazaakram commented on openedx_tagging/core/tagging/models/import_export.py
> +        choices=TagImportTaskState.choices,
This change should create new migrations.

2024-04-05 09:48 UTC, irtazaakram approved these changes

2024-04-05 13:21 UTC, feanil requested changes
I don't think we want to switch this from an enum to text choices, especially not translated, any translation should be happening upstream of the database.  @ormsbee can you take a look?

2024-04-05 13:38 UTC, feanil commented
I think instead you need to update the serializer here: https://github.com/openedx/openedx-learning/blob/1333cf6421e35b7e621fd5e10fc91c6a6f373634/openedx_tagging/core/tagging/rest_api/v1/serializers.py#L349

Currently it's trying to use the default serializer but that won't work with a tuple so you might need to make a custom serializer for just that field.

2024-04-05 14:32 UTC, ormsbee commented
@ChrisChV, @pomegranited, @bradenmacdonald: Could you please take a look at this? I'm not clear on the implications.

2024-04-05 18:38 UTC, bradenmacdonald commented
@feanil 

> I don't think we want to switch this from an enum to text choices, especially not translated, any translation should be happening upstream of the database.

I think it's unimportant but OK to translate this - the translations will show up in the Django Admin (only). Though generally I'm not in the habit of translating Django admin stuff for Open edX.

> Currently it's trying to use the default serializer but that won't work with a tuple so you might need to make a custom serializer for just that field.

There's no tuple involved - it's still a `CharField` and before and after this change it should be just a simple string value like `"error"` or `"success"` that's stored in MySQL or returned from the REST API. (Though in the middle, before this change, the Python-land view of this value was a special enum value object, not a plain string.)

I don't think any changes to the serializer are needed?

I reviewed the diff here - looks good. And since our REST API tests like

https://github.com/openedx/openedx-learning/blob/2ba5cf4cb26b13ff395d7010a9d0399fd3091b31/tests/openedx_tagging/core/tagging/test_views.py#L2621

are passing unchanged, this is good with me.

2024-04-05 18:38 UTC, bradenmacdonald approved these changes

2024-04-05 18:49 UTC, feanil reviewed
@bradenmacdonald thanks for taking a look, I missed that the initial model was also a Charfield mis-read the choices bit.  Thanks for the clarification.

2024-04-05 18:49 UTC, feanil approved these changes

2024-04-05 18:49 UTC, merged