feat: add get_collections api
openedx/openedx-learning pull request #214
Opened 2024-08-19 14:49 UTC by navinkarkera

2024-08-21 16:01 UTC, rpenido requested changes
@navinkarkera Could you add a test for this new function?

2024-08-22 14:19 UTC, rpenido approved these changes
LGTM :+1:
Thank you for your work, @navinkarkera !

- [x] I tested this using the instructions from https://github.com/openedx/edx-platform/pull/35324
- [x] I read through the code
- [x] ~I checked for accessibility issues~
- [x] Includes documentation

@pomegranited This is ready for CC review!

2024-08-23 05:06 UTC, pomegranited approved these changes
@navinkarkera :+1: with one nit/question for @ormsbee , but I'm fine with merging this as-is.

- [x] I tested this using the instructions on https://github.com/openedx/edx-platform/pull/35324
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] Includes documentation
- [x] <strike>User-facing strings are extracted for translation</strike> N/A

2024-08-23 05:19 UTC, navinkarkera commented on openedx_learning/apps/authoring/collections/api.py
> +    qs = Collection.objects.all()
@pomegranited I agree about making tests simpler, as you can see I had to make use of `self.assertQuerySetEqual` as the order was not matching in CI.

2024-08-23 10:29 UTC, navinkarkera commented on openedx_learning/apps/authoring/collections/api.py
> +    qs = Collection.objects.all()
Updated PR to order by `pk`, we can remove the commit if @ormsbee does not agree.

2024-08-23 14:57 UTC, ormsbee commented on openedx_learning/apps/authoring/collections/api.py
> +    qs = Collection.objects.all()
I originally made it sort by `pk` as a cheap, lazy way of sorting it by creation time. But I think it's a reasonable default sort in a lot of situations, so this is fine by me.

2024-08-27 04:31 UTC, merged

2024-08-27 04:31 UTC, openedx-webhooks commented
@navinkarkera 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-learning&entry.867055334=https://github.com/openedx/openedx-learning/pull/214&entry.1484655318=https://github.com/navinkarkera&entry.752974735=2024-08-19+14:49&entry.1917517419=2024-08-27+04:31&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->